### ISSUE TITLE
Add a href link to external database entry from ClearanceView

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/FairSync#31]
## Usecase
After the import, I want to make sure, that the entry was added correctly

## Problem
Finding the final entry can be timeconsuming

## Solution

- [x] Could you link the final entry in the final dialog?

![Image](https://github.com/user-attachments/assets/0b3f551b-e887-48a0-8d7d-98afde1c115d)

- [x] der Button sollte nach dem fertig merge, auch nicht mehr anklickbar sein, bzw. die aufschrift sollte irgendwie zu "successfully executed" geändert werden
- [x] Irgendwo auf der Seite sollten ein Button "Zum nächsten Eintrag" sein, der mich an den Anfang bringt, aber zum nächsten Eintrag in der List

zukünftige ideen
- [ ] Hier könnte auch eine log-preview oder eine diff-preiview angezeigt werden

**Comment by qknight** [comment]
Dieser Code kommt von Markus und ich denke es ist am besten er macht diese Erweiterung. @wellemut bitte spezifiziere wo genau drauf verlinkt werden soll, also mit einem Beispiel am besten.

**Comment by flosse** [comment]
Erledigt!

**Comment by wellemut** [comment]
Lieber @flosse 
Ich kann im finalen Screen noch nichts anklicken:
![grafik](https://github.com/user-attachments/assets/627995b4-c486-4162-9796-8816062b01fa)

Der Eintrag wurde definitiv erzeugt: https://www.kartevonmorgen.org/m/main/e/7dff7afe58fc4b1cb9d24c018ec49bf4?c=50.8260%2C5.6030&z=6.00&search=BadmintONEarth

arbeite ich vielleicht auf einer alten Version?

**Comment by wellemut** [comment]
> @wellemut glaube die daten werden nicht sofort angezeigt, sondern erst nach einer weile (auf KVM), hatte ich auch schon. 
> 
Mir geht es nur darum, das im letzten Screen kein Link zum finalen Eintrag auf der Karte erscheint, sondern ich diesen manuell auf der Karte suchen muss...

**Comment by wellemut** [comment]
New clarifying issue for my wish.
But in the Backlog as its not high prio: https://github.com/kartevonmorgen/FairSync/issues/48
