### ISSUE TITLE
Can we link to existing duplicates, in all dialogs?

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/FairSync#33]
Especially in this comparing dialog, I want to see the reference document, before  I merge something into it
![Image](https://github.com/user-attachments/assets/9605705f-4991-44f2-8b85-86bb4570b302)

Can we give a link next to the title to the existing entry?

**Comment by qknight** [comment]
the reference document is litteraly linked from (1.) on the left:

![grafik](https://github.com/user-attachments/assets/deb42f62-733b-4d01-82d7-325f518e4e68)

the (2.) is the import and

![grafik](https://github.com/user-attachments/assets/a8caa952-94bf-4329-a5f2-89230153b66d)

is (3.) the destination

given these 3 information sources you can always go back and forth with the state of the document. you are updating (1.) in essence but the output is in (3.) and so you can always see all the original documents and modify the 'new' document on (3.) until you are happy.

**Comment by wellemut** [comment]
Thanks for your answers.

Probably, the more I have seen, that the tool really works without mistakes, the less I need to check the original entry on the map.
