### ISSUE TITLE
Bug: duplicateView shows more than one selected_import

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/FairSync#34]
## Usecase
I need to know, which entries i have merged already and where to continue in the list in order not to merge things twice

## Problem
How do I know, that the first 2 entries are done already?
![Image](https://github.com/user-attachments/assets/feac1942-bb72-460c-a9bf-3b7524bb12ea)

## solution

- [ ] could you marke the entries green or grey, if they are done?

**Comment by qknight** [comment]
this is a **BUG**, the browsing view should show several imports, the view you are in is the duplicate view and it should show only exactly ONE import.

**can you reproduce this?**

**Comment by qknight** [comment]
Bis du das reproduziert hast, nehme ich mich aus dem ticket raus.

**Comment by wellemut** [comment]
This bug did not appear again.
Last time, I merged entries, they where deleted from the import-list as soon as they where uploaded into kvm.
![grafik](https://github.com/user-attachments/assets/c656f5ca-417a-466e-a98f-7fa77ef760d4)

And also the count of remaining imports gets down
![grafik](https://github.com/user-attachments/assets/d57f128e-75ce-4404-9a60-7cb4eb0f3a3c)
