### ISSUE TITLE
custom links should not get deleted by update

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/FairSync#37]
Entries on kvm can have a number of custom links, mostly used for social media 
i.e. 
![Image](https://github.com/user-attachments/assets/d4646bf9-a110-4fc0-a445-e2a2daab1876)
![Image](https://github.com/user-attachments/assets/ad4b5f5e-c30c-49b8-947e-3d48f797b94f)
https://dev.kartevonmorgen.org/m/main/e/65225ab4475a4a82b3ecdd09f80edb03?c=50.8129%2C5.6030&z=6.00&mapColorMode=gray&search=%C3%B6koligenta

The custom links are an array in the entries json:  https://dev.ofdb.io/v0/entries/65225ab4475a4a82b3ecdd09f80edb03
![grafik](https://github.com/user-attachments/assets/f2bb8940-b6d9-4419-a765-933af949d512)

But in the FairSync App the customs links dont appear when the entry is loaded
![grafik](https://github.com/user-attachments/assets/b79c8765-cec7-4f0d-a44b-533f0a74b91f)

## Bug
- Custom links, (or any content of the entries json) should not get deleted, unvisible and unnoticabel by the app, just because the fields are not yet implemented.

## Improvement
- beeing able to import at least up to 3 custom links would be nice, but obviously complicated in a csv

**Comment by qknight** [comment]
![grafik](https://github.com/user-attachments/assets/aa0c390d-78fd-4d99-9ef3-1ab3f3201716)

**Comment by wellemut** [comment]
Thank you @qknight 
Besonders begeistert bin ich jetzt, dass "Cusomlinks" icht mehr gelöscht werden, wenn man einen Eintrag mit custom links updated. Die bleiben erhalten. Das ist sehr cool! 

Also wenn ich eine csv in einen extistierenden Eintrag mit custom links merge, bleiben sie erhalten. 
Wenn ich  beim import einen 3. Eintrag mit custom links finde, bleiben nur die links des finalen Eintrags erhalten, der beim "merge" archiviert wird, dessen custom links gehen verloren.

Dazu ein neues Issue: 
- https://github.com/kartevonmorgen/FairSync/issues/49
