### ISSUE TITLE
Upload not working / csv broken?

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/FairSync#39]
@qknight @flosse can you find the problem in this csv?
[gwn200imp.csv](https://github.com/user-attachments/files/18220763/gwn200imp.csv)

The fairsync import does not take it 
![Image](https://github.com/user-attachments/assets/2eccb12d-e292-4391-8e80-8cd24cd6f541)

These are the first 200 entries from Gemeinschaftswerk Nachhaltigkeit (https://github.com/kartevonmorgen/FairSync/issues/5#issuecomment-2495558102). I got them by json and reformatted it into csv the whole night, but it did not work.

Die konsole sagt dazu folgendes: 
![Image](https://github.com/user-attachments/assets/6941ae2b-8949-42e5-8608-76453fc54654)

**Comment by qknight** [comment]
@wellemut we checked and it is UTF-8 as charset and mainly , as delimiter (you use ; as delimiter)

We also need to add an error messge to the home view.

**Comment by wellemut** [comment]
Danke dir @qknight . 
Das war ein guter Tipp. (Und Excel ist da leider überhaupt nicht transparent, wie etwas abgespeichert wird.)

Jetzt, wo ich auch den Dezimaltrenner der Koordinaten auf . umgestellt habe, geht es! 200 neue Testdaten
![grafik](https://github.com/user-attachments/assets/45069891-83c8-44bd-907c-5eed41e7db03)

habe es auch hier dokumentiert: https://github.com/kartevonmorgen/FairSync/wiki#csv-import
