### ISSUE TITLE
CSV import incomplete, tags are missing

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/FairSync#41]
## Problem
Only the coordinates of the new entry get loaded on the left side

![Image](https://github.com/user-attachments/assets/b29de1d8-b27d-4205-afd7-9c374cf59f71)

The csv item is ignored, as long as I choose the existing entry as destination.

csv entry has lots of hashtags: 
![Image](https://github.com/user-attachments/assets/0b0b9f3c-56cd-494c-823b-70edaed08a22)

but in the import dialog, they are just ignored. All tags are shown, as if both entry would have the same:
![Image](https://github.com/user-attachments/assets/270ca71a-513d-4367-b5a8-d9e8b71d3a5d)

Custom links also are ignored, not the one from csv on the left, both left and right belong to the right one.
![Image](https://github.com/user-attachments/assets/3fd0af0f-3ddc-4e8a-963c-066958fb039f)

### csv-entry attributes only visible when chosen as destination
Only when I choose the csv entry as new antry/ destination, it loads the existing data as comparasson. 

![Image](https://github.com/user-attachments/assets/0509195e-a3b4-45ed-af4a-dec72cf6c371)

![Image](https://github.com/user-attachments/assets/7f7c7da9-ad4e-418d-9ca2-a8d867dc31f6)

Really strange behaviour...

**Comment by wellemut** [comment]
Another Example:
csv entry has quite a long descriptoin
![grafik](https://github.com/user-attachments/assets/eb6b88b5-4934-429d-a180-4689ad3546c8)

and many tags:
![grafik](https://github.com/user-attachments/assets/bab473a9-ea32-432c-b808-7fa1eb623837)

In Merge Dialog:
- Short description gets loaded and coordinates too:
![grafik](https://github.com/user-attachments/assets/0c611ed4-ac59-4807-bb9b-8fc4c55e633a)

But Tags never appear!!
![grafik](https://github.com/user-attachments/assets/a9b926c4-9614-4738-a270-f5a41e64b0a3)

**Comment by wellemut** [comment]
Even when I dont have a duplicate to merge in, the contact details are half missed out:
![grafik](https://github.com/user-attachments/assets/227d621e-f897-475a-b9bd-6af99c8c84a6)

Content of csv:
![grafik](https://github.com/user-attachments/assets/cd9050fa-4125-4711-b1c3-706a427eb850)

Missing fields:
 - ZIP
 - Email
 - Phone

But in the Source-view of the csv entry, the data is clearly visible
![grafik](https://github.com/user-attachments/assets/2a5160a4-e065-43f3-b1c0-ab61a6ff20c6)
![grafik](https://github.com/user-attachments/assets/2a37ede3-3bba-4d16-bb0e-6571b4a47b9a)

**Comment by qknight** [comment]
i'll check this shortly

**Comment by qknight** [comment]
@wellemut hast du den import noch, wo der fehler auftritt?

**Comment by qknight** [comment]
[example-data.csv](https://github.com/user-attachments/files/18254184/example-data.csv)

CSV parser improved for all the missing fields. There is a bug in the tags editor which is a seperate concern from the import.

commit 7cb04ce92fe07f2b6ad2dc6afc7ff67e0dd724ab                                                                                                                                       
    CSV import: supporting state/contact_name/contact_email/contact_phone/opening_hours/image_link_url/zip, removed founded_on support

**Comment by wellemut** [comment]
@qknight unfortunately its still not working on https://fairsync.de/#
here are your test data
[2GWN20.csv](https://github.com/user-attachments/files/18256481/2GWN20.csv)

Es gibt hier nur einen csv Eintrag, der auf der linken seite korrekt angezeigt wird und oben ausgewählt ist. Warum werden ZIP,  Mail und pHone nicht gleich recht mit übernommen?

![Image](https://github.com/user-attachments/assets/21d5dd1c-dde3-43a4-9709-8546341e3b64)

**Comment by wellemut** [comment]
Das Problem sind wohl Leerzeichen in den Feldern, wie Joachim hier beschreibt: 
https://github.com/kartevonmorgen/FairSync/issues/46

**Comment by wellemut** [comment]
I close this issue, in favor of the more specific issue: https://github.com/kartevonmorgen/FairSync/issues/46
