### ISSUE TITLE
(Manuelles) Tag-Hinzufügen geht nicht

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/FairSync#45]
## Problem
Tags werden im Merge-Dialog zwar richtig angezeigt, aber
- manuell ergänzten Tags kommen nicht in der Karte an
- Via "Add all" hinzugefügte Tags kommen nicht auf der Karte an!
![Image](https://github.com/user-attachments/assets/8649cd36-6027-4e09-a297-556fc08e78bc)

Hashtag "Test" wurde manuell hinzugefügt

Scheinbar merkt es auch das tool selbst und lässt die Merge-Objekte immer in der Liste. die verschwinden da gar nicht:
![grafik](https://github.com/user-attachments/assets/35f53950-5f14-4db8-87f4-65146aafbef4)

Das Problem tritt IMMER auf, wenn Objekte verbunden werden.
Wenn ich nur eine CSV direkt importiere, kommen die Tags problemlos an.

Der Post-Request von FairSync an die Karte von morgen enthält nur die Ursprungstags. D.h. irgendwo zwischen Merge-View und Postrequest generierung gehen die manuell hinzugefügt und via "Add All" gemergeten tags verloren.

**Comment by qknight** [comment]
stimmt...

**Comment by wellemut** [comment]
@qknight das hier ist der aktuell störenste bug und daher der wichigste!

**Comment by wellemut** [comment]
Ich denke mal, technisch gesehen ist das immer das selbe Problem, egal ob es um die tags des zweiten Eintrags geht oder um manuell ergänzte.
- https://github.com/kartevonmorgen/FairSync/issues/47

**Comment by qknight** [comment]
This is fixed in 71b6510d1bd1dbaf6650bd1a4d7a669bf141a5d9
