### ISSUE TITLE
"Excecuted" says successful, but its not - tags missing!

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/FairSync#47]
Meine Tag-Auswahl beim zusammenführen eines csv imports in ein bestehenden Eintrag (merge) funktioniert, nur bei den tags nicht.

**Das muss ein FairSync interner Fehler sein, kein API-Problem, da Post-request schon falsch ist** daher kannst du @qknight vermutlich am besten helfen.

<-- Nicht reproduzierbar
Different description
![grafik](https://github.com/user-attachments/assets/bf6a4fcb-7d2a-48c5-a88f-471747011357)
i choosed
![grafik](https://github.com/user-attachments/assets/30848179-6f85-43bb-aba6-644321ed491d)
-->

mssing tags
![grafik](https://github.com/user-attachments/assets/175e6b46-f1a7-4d0b-8c9a-d445c76b32e4)
I added
![grafik](https://github.com/user-attachments/assets/002278d1-0a24-41d9-aaa5-d2429cbff496)

Eintrag vor Merege:
![grafik](https://github.com/user-attachments/assets/6aebed14-2cea-468b-8686-77894048609d)

Success notice:
![grafik](https://github.com/user-attachments/assets/b377a91a-a7fa-434a-a77d-b2817860a017)

## Problem
Short description was change, the tags not
![grafik](https://github.com/user-attachments/assets/f4111afe-4725-4a29-95e7-1a3393aa54a6)

**Comment by wellemut** [comment]
It could have been a singular issue. It did not appear again since then.

**Comment by wellemut** [comment]
It happend again!
these where the tags for merge, which where displayed correctly in the merge-view: 

`SDG4 sdg5 sdg7 sdg8 sdg9 sdg11 sdg12 sdg13 sdg15 sdg16 sdg17 gwn  HUMAN-RIGHTS AGRICULTURE SUSTAINABLE-FINANCE CLIMATE-PROTECTION SUSTAINABLE-LIFESTYLE SOCIAL-JUSTICE SUSTAINABLE-PROCUREMENT INTERNATIONAL-RESPONSIBILITY MOBILITY URBAN-DEVELOPMENT CIRCULAR-ECONOMY EDUCATION BIODIVERSITY GENDER-EQUITY PARTICIPATION CULTURAL-SOCIAL-CHANGE PEACE SUSTAINABLE-BUSINESS SUSTAINABLE-GOVERNANCE menschenrechte Landwirtschaft finanzen nachhaltig klimaschutz alternatives-wohnen nachhaltigesleben soziale-gerechtigkeit beschaffung nachhaltig entwicklungszusammenarbeit mobilität Stadtentwicklung kreislaufwirtschaft bildung artenvielfalt gender-equality beteiligung kultur wandel frieden sozialunternehmen sustainable-governance WORLD ASSOCIATION non-profit Verein`

But the put requst at the End only contained the initial tags from the existing entry:
![Image](https://github.com/user-attachments/assets/fc2e2dfe-9e13-4407-861f-0ff8f3933ea4)

**Comment by wellemut** [comment]
Ich denke mal, technisch gesehen ist das immer das selbe Problem, egal ob es um die tags des zweiten Eintrags geht oder um manuell ergänzte.
- https://github.com/kartevonmorgen/FairSync/issues/45

**Comment by wellemut** [comment]
@qknight von den 20 Einträgen, die ich im 4. durchgang importiert habe, waren 9 Dupletten. So war bisher immer mein Schnitt. Wobei nur 6 vom Llama Checker automatisch erkannt wurden. Die anderen 3 Lagen teilweise zu weit weg, du wusst ich dann durch zufall, dass es sie schon gibt, oder der Titel war einfach anders.
**Den Vergleichsradius musst du immer auf 1000 m setzen, sonst findet der keine Dupletten.**

Die folgenden 9 Dubletten habe ich nicht verarbeitet/importiert, da die Stichworte ja nicht funktionieren und damit du Testdaten hast, die definitiv dupletten haben:
![grafik](https://github.com/user-attachments/assets/7198bd76-9978-467e-bf98-0b5f8eaa4d6a)
[4GWN20 - dubletten.csv](https://github.com/user-attachments/files/18269520/4GWN20.-.dubletten.csv)

- [ ] Bitte fixe das Hashtag upload problem
- [ ] und importiere testweise diese 9 Einträge

(Beim BUNDJugend MV gibt es zwar jetzt nur noch ein Eintrag, statt vorher drei, durch das archivieren der anderen 2 haben wir aber auch deren hashtags komplett verloren)

**Comment by qknight** [comment]
@wellemut the fix was quite simple:

I just forgot to write the intermediate state to the final output request:

![grafik](https://github.com/user-attachments/assets/ac9c817f-fbf2-429e-a9ac-27fc99285186)

This is fixed in 71b6510d1bd1dbaf6650bd1a4d7a669bf141a5d9

**Comment by qknight** [comment]
@wellemut i imported the 9 entries with one problem:

![grafik](https://github.com/user-attachments/assets/54f91d1e-6fa6-433e-9064-1af06cd7c7f7)
