### ISSUE TITLE
duplicated ratings: rating won't get deleted when deselcted and updates seem to add duplicated ratings

### ISSUE THREAD

**Issue by qknight** [kartevonmorgen/FairSync#52]
![grafik](https://github.com/user-attachments/assets/21917cc2-4759-41b3-ac08-af5475b1f205)

**Comment by wellemut** [comment]
@qknight das problem scheint zu sein, das ratings, die bereits beim Zieleintrag sind, nochmals in den Zieleintrag automatisch rein kopiert werden, damit also einfach verdoppelt werden.

![grafik](https://github.com/user-attachments/assets/f0df1c57-aad7-420a-b26e-f5e7b52d76cf)

**Comment by flosse** [comment]
Should be fixed in https://codeberg.org/fairsync/importer-prototype/commit/9b0a01e5b4fe1bb37b89463a859fa9e781ae4d25
